name: 'oil_project_dw'
version: '1.0.0'

profile: 'oil_project_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
    "dbt_date:time_zone": "America/Sao_Paulo"

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  oil_project_dw:

    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: table
      +schema: intermediate

    mart:
      +materialized: table
      +schema: mart

      core:
        +schema: marts_core
      analytics:
        +schema: marts_analytics
